### ISSUE TITLE
CloudFront tokens incompatible with vod module remote upstream?

### ISSUE THREAD

**Issue by bson** [kaltura/nginx-secure-token-module#24]
I'm trying to get an experimental setup going in AWS.  Currently the configuration consists of:

CloudFront backed by an origin:

EC2 instance
nginx built with:
- nginx-vod-module
- nginx-secure-token-module
- headers-more-nginx-module
pulling content out of an S3 bucket

This works fine until I try to enable cloudfront URL tokens.

Config with tokens disabled - works fine:

    #user  croll;
    worker_processes  1;
    daemon off;

    error_log  logs/error.log;
    error_log  logs/error.log  notice;
    error_log  logs/error.log  info;
    error_log  logs/error.log  debug;

    pid        logs/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  logs/access.log  main;

        sendfile           on;
        tcp_nopush         on;
        keepalive_timeout  65;
        gzip               on;

        upstream vod_s3 {
            server vod-s3-test.s3-us-west-1.amazonaws.com:80;
            #server localhost:8186;
        }

        server {
            listen       80;
            server_name  localhost;

            location ^~ /__child_request__/ {
                internal;
                vod_child_request;
            }

            location ^~ /public/ {
                vod hls;
                vod_mode remote;
                vod_moov_cache moov_cache 512m;
                vod_secret_key "BigSecretHere$vod_suburi";
                #vod_hls_encryption_method aes-128;
                vod_align_segments_to_key_frames on;
                vod_segment_count_policy last_rounded;
                vod_hls_encryption_method none;
                vod_child_request_path /__child_request__/;
                vod_upstream vod_s3;
                vod_upstream_host_header vod-s3-test.s3-us-west-1.amazonaws.com;
                #gzip_types application/vnd.apple.mpegurl;
                vod_bootstrap_segment_durations 2000;
                vod_segment_duration 5000;
                vod_segments_base_url "http://d22ovrjxux10n8.cloudfront.net:80";

                #TOKEN GENERATION
                #secure_token cloudfront;
                #secure_token_window 7200;
                #secure_token_expires_time 100d;
                #secure_token_query_token_expires_time 1h;
                #secure_token_avoid_cookies on;
                #secure_token_cloudfront_private_key_file "/home/ec2-user/rsa-xxxxxxxxxx.pem";
                #secure_token_cloudfront_key_pair_id "xxxxxxxxxx";

                #more_set_headers 'Access-Control-Allow-Headers: *';
                #more_set_headers 'Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range';
                #more_set_headers 'Access-Control-Allow-Methods: GET, HEAD, OPTIONS';
                #more_set_headers 'Access-Control-Allow-Origin: *';
            }

            location ^~ /status/ {
                vod_mode remote;
                vod_status;
                vod_moov_cache moov_cache 512m;
                vod_secret_key "zzzzzzzzzzzzzzzzzzzzzzz$vod_suburi";
                vod_hls_encryption_method none;
                vod_child_request_path /__child_request__/;
                vod_upstream vod_s3;
                #gzip_types application/vnd.apple.mpegurl;
            }
        }
    }

If I try to enable tokens by uncommenting the config under "TOKEN GENERATION" it fails with:

    nginx: [emerg] "vod_upstream" directive cannot be loaded in /usr/local/nginx/conf/nginx.conf:88

Indicentally, gzip_types has a similar problem.

Is this due to a basic incompatibility when using the nginx-vod-module as an upstream remote?
Any thoughts on workarounds?

nginx and the modules are all cloned from github and recent (as in a day or two old).

**Comment by erankor** [comment]
This error doesn't seem related to the tokens, if you are using the latest version of nginx-vod-module, vod_upstream is no longer supported, see - https://github.com/kaltura/nginx-vod-module/blob/master/CHANGELOG.md

**Comment by bson** [comment]
Aha, that explains it.  My git repos needed a fetch.  Now I get sensible config errors.  Thanks!
