### ISSUE TITLE
how does possibleto generate valid token ? 

### ISSUE THREAD

**Issue by msdev100** [kaltura/nginx-secure-token-module#25]
Hello , I appreciate to response us promptly . Actually i try to run complete NGINX-Secure-Token module .However i have problem on Token side . I would like o elaborate my problem its nice of you to help me to solve my problem in short time . Indeed I am going to use URI encryption . How does possible to generate valid token to perform function of URI encryption . Now i have problem  to parse a module to run : Pls look at below .

http://192.168.249.132:8800/11.mp4?token=4IH6Ycedmlxpb45PivDgEw&expire=1437523198
'Do you think possible to work Nginx-secure-token module with such as this pattern aforementioned?

**Comment by erankor** [comment]
I'm sorry but I don't quite understand the question. 
A couple of clarifications about the module though:
1. The purpose of this module is for propagating the token from the manifest request to the segments requests, in HTTP based streaming protocols (HLS, HDS, DASH, MSS). The sample URL you provided looks like progressive download, so it's not relevant in this case
2. The module does not support arbitrary token formats, it supports Akamai tokens and CloudFront tokens, the token sample you provided does not look like either of them
