### ISSUE TITLE
URI encryption

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-secure-token-module#27]
Hi, 

can you please create some examples with URI encryption ? 

i use php to create encrypted link, i get something like this 
http://example.com/video/JGIYQUGGvNRycbZ2kXp9ZN6oTSOmXRbc0xI_BV1VOLg

such link looks correctly?

or need use urls like this ? 
http://example.com//video/JGIYQUGGvNRycbZ2kXp9ZN6oTSOmXRbc0xI_BV1VOLg/long.mp4/master.m3u8
 Please show some simple examples .

**Comment by arty777** [comment]
I already use native nginx secure_link module with nginx-vod-module , all work fine

**Comment by erankor** [comment]
did you see this example:
https://github.com/kaltura/nginx-secure-token-module#uri-encryption

The URL can be either the first or the second, whatever you choose, the encrypted part is determined by the regular expression you define on the location. 
With the sample configuration above, an encrypted URL looks like this:
```
http://domain/hls/p/2035982/sp/203598200/serveFlavor/entryId/0_nf0aybik/g5at6bD2WsUEeR3tRGgzW4LUE5uQvdkl_bUbeA_J5M1RVd5nTWfb0JSPdvam9ONAx4y5fnVT8
```
(i.e. everything after the entry id is encrypted, including the extension)

**Comment by nvchungdl** [comment]
Hello,

How creat encrypted string in php ? 
Like 
`g5at6bD2WsUEeR3tRGgzW4LUE5uQvdkl_bUbeA_J5M1RVd5nTWfb0JSPdvam9ONAx4y5fnVT8 
` 
in uri encryption

**Comment by erankor** [comment]
https://github.com/kaltura/nginx-secure-token-module/blob/master/scripts/encryptUrl.php

**Comment by nvchungdl** [comment]
Hi, please help me correct the config. 

nginx
`location ~ ^/hls/([^/]+)/(.*) {
 alias /home/mp4/;
        vod hls;
        vod_mode local;

        vod_bootstrap_segment_durations 3500;
        vod_secret_key "password$1";

        secure_token_encrypt_uri on;
        secure_token_encrypt_uri_key 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f;
        secure_token_encrypt_uri_iv 00000000000000000000000000000000;
        secure_token_encrypt_uri_part $1;
        secure_token_types application/vnd.apple.mpegurl;`

php

`$BASE_URL = 'http://mydomain/hls/';
$ENC_URL = 'passwordTest.mp4';
$ENC_KEY = pack("H*", '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
$ENC_IV = pack("H*", '00000000000000000000000000000000');`

php result: http://mydomain/hls/dUDe0ktD5QrUSLn_ts0HTSuCbRzilsSiqbDd1wqzKLU/index.m3u8 

error log

`ngx_file_reader_update_state_file_info: "/home/mp4/" is not a file, client: x.x.x.x, server: , request: "GET /hls/dUDe0ktD5QrUSLn_ts0HTSuCbRzilsSiqbDd1wqzKLU/index.m3u8 HTTP/1.1"`

**Comment by erankor** [comment]
I checked it out, it happens because you use alias in a regex location, so nginx expects the alias value to be the full path of the file (it doesn't add the filename to it). To solve that, you need to add $1 to the alias:
```
alias /home/mp4/$1;
```
However, what you will get then is that nginx will evaluate $1 to the encrypted value - it will look for /home/mp4/dUDe0ktD5QrUSLn_ts0HTSuCbRzilsSiqbDd1wqzKLU.
I created a patch for this here - https://github.com/kaltura/nginx-secure-token-module/pull/45, this will make $1 evaluate to the decrypted file name. Please try it out and let me know if it works for you.
I'm not sure this solution makes sense in all cases - since the fact the location regex matches the incoming encrypted uri, doesn't necessarily mean it will match the decrypted uri. So I will probably add some conf flag to enable/disable this behavior.

**Comment by erankor** [comment]
Also, please avoid reusing existing issues for unrelated problems.

**Comment by nvchungdl** [comment]
Thank you erankor, i will open new issue if still have problem

**Comment by erankor** [comment]
@nvchungdl, did you try this pull (https://github.com/kaltura/nginx-secure-token-module/pull/45)? did it work for you?

**Comment by nvchungdl** [comment]
@erankor 
I didn't work when i fix like you said
`2017/02/28 14:59:40 [error] 21155#21155: *2 ngx_file_reader_update_state_file_info: open() "/home/mp4/EFKyK243JzVCQkK0lRib1RIn-Hgbyqp7h11fhBgYQIU/test/Test.mp4" failed (2: No such file or directory), client: 14.187.205.68, server: , request: "GET /test/EFKyK243JzVCQkK0lRib1RIn-Hgbyqp7h11fhBgYQIU/index.m3u8 HTTP/1.1", host: "188.166.227.234"`

But it worked when i removed /hls/ and use root replace alias. Like below

`    location ~ ^/([^/]+)/(.*) {
        root /home/mp4/;
        vod hls;
`

**Comment by erankor** [comment]
@nvchungdl, can you paste the config that didn't work for you with the patch? I'm just considering whether to merge it or not, and when I tested it, it solved the problem

**Comment by nvchungdl** [comment]
@erankor 
nginx config
`    location ~ ^/test/([^/]+)/(.*) {
        root /home/mp4/$1;
        vod hls;
        # vod settings
        vod_mode local;
        vod_align_segments_to_key_frames on;
        vod_bootstrap_segment_durations 3500;
        #vod_base_url http://188.166.227.234/proxy;
        vod_hls_absolute_index_urls off;

        secure_token_encrypt_uri on;
        secure_token_encrypt_uri_key 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f;
        secure_token_encrypt_uri_iv 00000000000000000000000000000000;
        secure_token_encrypt_uri_part $1;
        secure_token_types application/vnd.apple.mpegurl;

        #vod_mode remote;
        #vod_upstream_location /remote;

        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
    }
`

error log
`2017/03/01 15:51:45 [error] 21155#21155: *141 ngx_file_reader_update_state_file_info: open() "/home/mp4/EFKyK243JzVCQkK0lRib1RIn-Hgbyqp7h11fhBgYQIU/test/Test.mp4" failed (2: No such file or directory), client: x.x.x.x, server: , request: "GET /test/EFKyK243JzVCQkK0lRib1RIn-Hgbyqp7h11fhBgYQIU/index.m3u8 HTTP/1.1", host: "x.x.x.x"
`

**Comment by Offek** [comment]
Hello,
I'm experiencing a similar issue where the encrypted uri is being decrypted only when using `root`.
If I use `alias`, the string remains encrypted.
