### ISSUE TITLE
MD5_DIGEST_LENGTH not defined

### ISSUE THREAD

**Issue by bson** [kaltura/nginx-secure-token-module#30]
I'm trying to build nginx with nginx-vod-module and nginx-secure-token-module, but get an undefined symbol:

        make -f objs/Makefile
        make[1]: Entering directory `/home/bson/evs-nginx-vod/.build/nginx'
        cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/\
core -I src/event -I src/event/modules -I src/os/unix -I /home/bson/evs-nginx-vod/.build/ngx_devel_kit/objs -I objs/addon/ndk -I /home/bson\
/evs-nginx-vod/.build/lua-nginx-module/src/api -I objs -I src/http -I src/http/modules -I /home/bson/evs-nginx-vod/.build/ngx_devel_kit/src\
 -I /home/bson/evs-nginx-vod/.build/ngx_devel_kit/src -I /home/bson/evs-nginx-vod/.build/ngx_devel_kit/objs -I objs/addon/ndk -I src/mail \
                        -o objs/addon/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.o \
                        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c: In function ‘ngx_http_secure_token_d\
ecrypt_uri’:
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:201: error: ‘MD5_DIGEST_LENGTH’ undec\
lared (first use in this function)
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:201: error: (Each undeclared identifi\
er is reported only once
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:201: error: for each function it appe\
ars in.)
        cc1: warnings being treated as errors
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:201: error: unused variable ‘md5hash’
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c: In function ‘ngx_http_secure_token_e\
ncrypt_uri’:
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:321: error: ‘MD5_DIGEST_LENGTH’ undec\
lared (first use in this function)
        /home/bson/evs-nginx-vod/.build/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.c:321: error: unused variable ‘md5hash’
        make[1]: *** [objs/addon/nginx-secure-token-module/ngx_http_secure_token_encrypt_uri.o] Error 1
        make[1]: Leaving directory `/home/bson/evs-nginx-vod/.build/nginx'
        make: *** [build] Error 2

Looking through nginx, it doesn't define MD5_DIGEST_LENGTH anywhere.  In fact, ngx_md5.h uses uchar[16] for the digests.  The only place I find it defined on the system is in /usr/include/openssl/md5.h, but this doesn't seem to be anywhere in the include chain.

Here's the nginx configure options (excluding module list):

    --with-http_secure_link_module --with-file-aio --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-debug --with-threads

And the complete list of modules:
https://github.com/openresty/headers-more-nginx-module.git
https://github.com/kaltura/nginx-vod-module.git
https://github.com/kaltura/nginx-secure-token-module.git
https://github.com/openresty/lua-nginx-module.git
https://github.com/simpl/ngx_devel_kit.git
ttps://github.com/openresty/set-misc-nginx-module.git

Not all the latest, but nginx and the two kaltura modules are current pulls from master.

It seems either MD5_DIGEST_LENGTH is obsolete and we need to define our own, or it's an undocumented dependency not caught by autoconf.

**Comment by erankor** [comment]
try to add to ngx_http_secure_token_encrypt_uri.c after the `#include`s:
```
#ifndef MD5_DIGEST_LENGTH
#define MD5_DIGEST_LENGTH (16)
#endif // MD5_DIGEST_LENGTH
```
if that fixes the issue, I'll merge it

**Comment by bson** [comment]
Yep, that fixes it.

**Comment by erankor** [comment]
Merged, thanks
