### ISSUE TITLE
unknown directive 

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-secure-token-module#33]
akamai_token_validate on;
akamai_token_validate_key 1234;
akamai_token_validate_uri_filename_prefix encryption;
akamai_token_validate_uri_filename_prefix index;

this config opt does't work 

[emerg] unknown directive "akamai_token_validate"

It's normal ?  I get config example for "Encrypted HLS with token security on the encryption key"

**Comment by jessp01** [comment]
Hi @arty777,

This directive belongs to the [nginx-akamai-token-validate-module] (https://github.com/kaltura/nginx-akamai-token-validate-module/search?utf8=%E2%9C%93&q=akamai_token_validate) so when compiling Nginx, you need to compile it with this module as well as the nginx-secure-token-module.

**Comment by arty777** [comment]
Nice , thank you for quick responce
