### ISSUE TITLE
How to protect forwarding tokens between people?

### ISSUE THREAD

**Issue by PapiCZ** [kaltura/nginx-secure-token-module#46]
Hello guys.
Customer in my service can pay for access to private stream (HLS). I need to have one token per one real person. Because now person A can send his token to person B. So only one person will pay for private stream, but stream can be watched by more people with the same token.
Dynamic token is not solution, because person A can make his own app to send token to his friends.

Any solution?

**Comment by erankor** [comment]
You can use IP restriction on the token (see `ip_address` under CloudFront / Akamai), this will make this attack significantly harder. Note that in some cases IP restriction can cause issues, e.g. we've seen cases in which an organization uses multiple proxies to access the Internet, and this can make the IP address of the user change during playback. If that happens, the token will have IP X while the request will have IP Y and it will fail.
Another possible solution to this issue is to use DRM, but that is a larger effort to implement.

**Comment by PapiCZ** [comment]
I don't think IP restriction is good idea. Because todays a lot of people can share one IP address. So if friends live in one house, this solution is going to fail.
I don't need 100% solution, but I need solution w/o problems and let's say about 80% reliable

**Comment by erankor** [comment]
Another possibility is to use cookie tokens instead of query tokens, that will make it a bit harder to hack, but still possible (and also, we've seen that cookies do not work with Safari).
At the end, consider that if both people have the same IP address, how can the server know which request came from user A and which request came from user B? One way is to use cookies, as I wrote, another may be to use the user agent (since it's sensitive to OS/Browser versions it's likely to be different), but there is no way to sign it with an Akamai/CloudFront token afaik (and also, it is possible that the manifest request will use user agent A and the segment requests will use user agent B)
So I don't think there's a very good solution to this other than DRM.

**Comment by PapiCZ** [comment]
I have one 90% solution, but I am not sure if it is effective.
As you know, HLS split stream into small files that have names 1.....∞.ts. My solution is to have in MySQL DB last number of file that was sent to user. And on every request use reverse proxy that runs PHP script that will check if file was already sent to user.

### For example
We have user A and user B. User A paid for 30 minutes of private stream, but he wants to send his private token to user B. User A turns on stream and send his private key to user B. User B insert private key to cookies or query string.
Now users A and B will receive index.m3u8. User A wants to get for ex. file 100.ts. Now PHP script is going to check if last received file was < 100. All it's ok so there's no problem. But now user B wants to receive 100.ts. Last sent file for private key was 100, so server will fuck him.
Of course user B can be faster than user A, but now it's fault of user A, because stream is for both user unwatchable.

**Comment by erankor** [comment]
This solution will only work if you are serving the streams directly from nginx, it won't work with a CDN / caching proxy. I don't know how many users you are expecting, if you have many, you must use a CDN. However, if the number of users is not very large this can work.
Another problem with this solution is seek - the user won't be able to seek forward and then backward.

**Comment by PapiCZ** [comment]
For start I expect about 1000 users :)

**Comment by PapiCZ** [comment]
Can you tell me how to set up nginx for private HLS?
I want something like this: Everytime when user should get new token I wanna call reverse proxy (or bash script) which tells to nginx if user can get access (and token).

### For example
1. User send first HTTP request to http://localhost/stream.m3u8
2. Because user doesn't have token is called reverse proxy
3. Reverse proxy returns code 200 and user will get token with expiration time 10 seconds
4. Now user getting files with the same token for 10 seconds without calling reverse proxy
5. After 10 seconds user needs to get new token and is repeated point 2, 3, 4, 5, ......

**Comment by erankor** [comment]
You can try with access_by_lua maybe, but this doesn't make much sense to me, if you are calling some upstream every time to validate the request, then why do you need a token? 
Normally when tokens are used no additional security checks are performed - all checks are performed up front, if they pass a token is generated, and from this point the only validation is for the token

**Comment by PapiCZ** [comment]
I don't wanna validate every request. I wanna validate every first request every 10 seconds.
So... User will come to stream and he wants to get index.m3u8. This is the time when I need to check if user can get access token. If he get the token, I don't need to check it for 10 seconds (only token check). After 10 seconds user's token expired and he needs to get new one. This is the time, when I need to check if user can get new access token again.

**Comment by erankor** [comment]
The default segment duration for HLS is 10 sec, so with that, after the initial buffering of the player, every request == every 10 seconds. I don't know which segment duration you had in mind, but usually the values that are used are at least 4 sec, and in that setting there isn't a very big difference between every request and every 10 sec. 

Other than that:
1. Unless we are talking about live, don't really understand how you planned to give the user a new token, in VOD the player requests the index.m3u8 at most once per bitrate. In live there are other complexities, e.g. you can't change the url of a segment when the live window rotates.
2. Assuming it is important that you don't check a user more than once every 10 sec, I still don't think there's a reason to use 2 separate mechanisms, you can use access_by_lua (or something similar) for the access check against the upstream, and just cache the result for 10 seconds. srcache-nginx-module can probably do the job (I never used this module myself), but maybe there are other ways to do that

**Comment by PapiCZ** [comment]
Thanks for your advices. I think I will use access_by_lua :)

Btw.. we're talking about 1s segment duration, because it's low latency HLS :)

**Comment by PapiCZ** [comment]
Last question... Do you know answer for this issue?
https://github.com/openresty/lua-resty-mysql/issues/57

**Comment by erankor** [comment]
I believe arrays in Lua start at 1, maybe that's why it doesn't work for you.
Anyway, closing this issue
