### ISSUE TITLE
can protect index.m3u8 by token?

### ISSUE THREAD

**Issue by chy168** [kaltura/nginx-secure-token-module#48]
Hello guys,

I'm using nginx-secure-token-module for token validation via 'secure_token_cloudfront'.
In my environment, I don't actually use CloudFront as my CDN. I'm trying to build a direct access solution for myself.

My config:
```
        location ~ ^/streaming/tokened/.* {
                        root /data/;

                        # security token
                        secure_token $token;
                        secure_token_types application/vnd.apple.mpegurl;
                        secure_token_expires_time 100d;
                        secure_token_query_token_expires_time 1h;

                        # encrypted hls
                        vod hls;
                        vod_secret_key "mukkaukk$vod_filepath";
                        vod_hls_encryption_method aes-128;

                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                        add_header Access-Control-Allow-Origin '*';

                        expires 100d;
                }
```

This work perfectly on my player (via: /streaming/tokened/test01.mp4/index.m3u8) and I can see the segment URL inserted signature automatically by secure-token-module in access log.

Here are my questions:

Can I protect "/streaming/tokened/test01.mp4/index.m3u8" by token also?
i know we can protect index.m3u8 by header checking. For complex authentication, I would like to write API to return player with signed token and index.m3u8 URL. Then the player can access index.m3u8 with token validation?

Thank you!

**Comment by erankor** [comment]
This module does not validate the CDN token, its purpose is to embed CDN tokens in the URLs returned inside the manifests (m3u8 in the case of HLS). 
Since you are not using a real CDN, you'd need some module in the nginx server to make sure the token is valid. We have such a module for Akamai tokens that you can use - https://github.com/kaltura/nginx-akamai-token-validate-module (we don't have one for CloudFront)
If you use this module, it will protect both the manifest and segments with tokens - requests with no/invalid token will return error 403. 
The tokenized URL for the index.m3u8 will normally be created externally by your application, as you wrote, and ngx-secure-token-module will make sure to generate tokens for the segment URLs.

**Comment by chy168** [comment]
thanks for you information. I'm switching to akamai token validate module.

My configuration is just like below:

```
        location ~ ^/streaming/tokened/.* {

        root /data/;

            # security token
            secure_token $token;
            secure_token_types application/vnd.apple.mpegurl;

            secure_token_expires_time 100d;
            secure_token_query_token_expires_time 1h;

            akamai_token_validate on;
            # client-secret-testing => 636c69656e742d7365637265742d74657374696e67
            akamai_token_validate_key 636c69656e742d7365637265742d74657374696e67;
            akamai_token_validate_uri_filename_prefix encryption;
            akamai_token_validate_uri_filename_prefix index;

			# encrypted hls
			vod hls;
			vod_secret_key "mukkaukk$vod_filepath";
			vod_hls_encryption_method aes-128;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';

			expires 100d;
		}
```

Once I access my "/streaming/tokened/test01.mp4/index.m3u8", I got 403 status code.
I guess the module works and it deny me from accessing directly.
The new problem is, how can I debug to check what's going on at the token validation / URL correctly?

I have already turn on debug by:
```
error_log  logs/error.log debug;
````

Thanks!

**Comment by erankor** [comment]
gdb :) unfortunately this module does not output any debug messages.
I suggest you start with a rather permissive token - create a token with `acl=/*`, `st=0` and `exp=2147483647`, once this token works, you know the signature is correct, and you can move to more strict tokens.
I didn't understand your question about client-token/access-token.

Btw, as I just looked at the code of nginx-akamai-token-validate-module (didn't touch this module for a long time...), I noticed a small leak there, so better re-pull latest master.

**Comment by chy168** [comment]
About the client-token/access-token question,
since I have't never used Akamai, I see the authentication token used "access token" and "client token" as text to encrypt in the [Akamai Client Authentication document](https://developer.akamai.com/introduction/Client_Auth.html). 
I expect "nginx-secure-token-module" use the same algorithm to calculate the signature.
Is that the correct "token algorithm" I should test?

BTW, I will try more easier acl to test it, thank you!

**Comment by erankor** [comment]
The page you referred to is talking about tokens that secure Akamai API, these are not the tokens that protect content. 
The tokens we are using look something like: `token=st=1234~exp=5678~acl=/abc/*~hmac=abcd`
We are using this php code to generate them:
https://github.com/kaltura/server/blob/Lynx-12.14.0/alpha/apps/kaltura/lib/storage/urlTokenizers/kAkamaiSecureHDUrlTokenizer.php

**Comment by chy168** [comment]
ohhh, thank you @erankor!
I will try to generate the token follow by the php code.
May I confirm with you that if I generated the token, for example:

```
token=st=1492154521~exp=1492155121~hmac=c9de5fb750b99c55bb57b7d917d878b7f3c7650928eba211a70a040a1169de5f
```

Could I just append it to my URL?

```
/streaming/tokened/test01.mp4/index.m3u8?token=st=1492154521~exp=1492155121~hmac=c9de5fb750b99c55bb57b7d917d878b7f3c7650928eba211a70a040a1169de5f
```

is this correct and expected behavior?

**Comment by erankor** [comment]
yes, this looks right, you also need `secure_token $token` in your conf (`secure_token_akamai` only defines an nginx var that evaluates to the token, `secure_token` associates this var with a specific location)

**Comment by chy168** [comment]
Hi @erankor, thank you for the great suggestion!
I can generate validate token and works great with `nginx-secure-token-module`!

I have another question after enabling token validation, i use config by
```
secure_token_avoid_cookies off;
```

The test flow as below:

1. Request self-generated URL: /streaming/tokened/test01.mp4/index.m3u8?token=st=1492352580~exp=1492525380~acl=/streaming/tokened/test01.mp4/*~hmac=4dee8d79d1b1cae85f4da48d9d0f73b572efae9f13c1c3b35cd642604b7519b9
2. Check the Set-Cookie header in the response and store it
3. Use the stored token make the 2nd request to video segment
4. Get 403 permission denied

I notice the signature generated in cookie is different from mine, could you please advice? thanks!

**Comment by erankor** [comment]
nginx-akamai-token-validate-module does not support cookie tokens, but other than that, I wouldn't recommend the use of cookies, Safari by default blocks the cookies for any domain other than the domain of the page (so, if the video is delivered from domain X and the page from domain Y it won't work) and we also experienced some problems with cookies in Firefox

**Comment by chy168** [comment]
In my scenario, i will deliver video content to app, and i think cookie token can help us preventing us from sniffering URL by attacker. For this purpose, would you suggest other solution? (now using: HTTPS + Encryption + HTTP auth header checking)

regarding to cookie tokens, what module or function would support? I think after I finished my work, I could help to enhance nginx-akamai-token-validate-module document.

Thanks!

**Comment by erankor** [comment]
Check out this branch - https://github.com/kaltura/nginx-akamai-token-validate-module/pull/7
I generalized the module a bit so that it gets the token value from an nginx variable. 
So, you can now write:
```
            akamai_token_validate $cookie_token;
            akamai_token_validate_key 1234;
            akamai_token_validate_uri_filename_prefix encryption;
            akamai_token_validate_uri_filename_prefix index;
```

**Comment by xslightz** [comment]
@erankor how can I call that class you posted? I tried searching but no idea how to call it to generate the token.

**Comment by jessp01** [comment]
Hi @xslightz,

Are you talking about https://github.com/kaltura/nginx-secure-token-module/blob/master/scripts/encryptUrl.php?
It's a PHP script which includes a usage message:
https://github.com/kaltura/nginx-secure-token-module/blob/master/scripts/encryptUrl.php#L5
You will need PHP CLI with either the mcrypt or the openssl extensions loaded.

**Comment by erankor** [comment]
@jessp01, I think the question is about kAkamaiSecureHDUrlTokenizer.php. 
@xslightz, this class is part of the Kaltura server, and I assume you want to create tokens without a Kaltura server. In that case, what I suggest is that you'll copy the first few classes in that file to your project (up to `class kAkamaiSecureHDUrlTokenizer`) - this part of the code is a generic code written by Akamai for generating these tokens (you can probably download it from their site as well...)
Then, to use it, you need to do something like this:
```
		$c = new Akamai_EdgeAuth_Config();
		$c->set_acl('/hls/video/*');		// the part of the URL path to sign
		$c->set_window(60);			// expiration time for the token in sec
		$c->set_start_time(time());		// token start time
		$c->set_key('abcd');			// token secret signing key
		
		$g = new Akamai_EdgeAuth_Generate();
		echo $g->generate_token($c);
```

**Comment by jessp01** [comment]
Sorry, I missed the reference to https://github.com/kaltura/nginx-secure-token-module/issues/48#issuecomment-294093738 when looking before...  Removed my comment as this obviously about https://github.com/kaltura/server/blob/Mercury-13.11.0/alpha/apps/kaltura/lib/storage/urlTokenizers/kAkamaiSecureHDUrlTokenizer.php and what I assumed before.

**Comment by xslightz** [comment]
@erankor thanks, I will look into that.

**Comment by ylouylou** [comment]
Could someone post a complete kaltura.conf and nginx.conf file please?
