### ISSUE TITLE
Problem with whitespace!

### ISSUE THREAD

**Issue by longtranthang** [kaltura/nginx-secure-token-module#52]
Hi all,

I have problem when my file have whitespace in path, how can i fixed it? Decrypted is ok, but encrypted failed.

Original file path: https://example.com/Cong suat dien/01_360.mp4

Thank in advance.

> #EXTM3U
> #EXT-X-TARGETDURATION:10
> #EXT-X-ALLOW-CACHE:YES
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:1
> #EXTINF:10.000,
> https://example.com/EkVN0ppqbSIeojyNRocD-Q suat dien/01_360.mp4/seg-1-v1-a1.ts
> #EXTINF:10.000,
> https://example.com/EkVN0ppqbSIeojyNRocD-Q suat dien/01_360.mp4/seg-2-v1-a1.ts
> #EXTINF:10.000,
> https://example.com/EkVN0ppqbSIeojyNRocD-Q suat dien/01_360.mp4/seg-3-v1-a1.ts
> #EXTINF:9.755,
> https://example.com/EkVN0ppqbSIeojyNRocD-Q suat dien/01_360.mp4/seg-4-v1-a1.ts
> #EXT-X-ENDLIST

**Comment by erankor** [comment]
I think the solution is on nginx-vod-module's side, please check with this pull - https://github.com/kaltura/nginx-vod-module/pull/650

**Comment by longtranthang** [comment]
Thank you.

Finally, i replace all whitespace with underscore :)

**Comment by erankor** [comment]
@longtranthang, did you try the pull request? it didn't work for you?

**Comment by mcml91** [comment]
> @longtranthang, did you try the pull request? it didn't work for you?
Hey,

I applied the pull, this did not resolve the issue.
