### ISSUE TITLE
Set expire time for secure_token_encrypt_uri

### ISSUE THREAD

**Issue by hien** [kaltura/nginx-secure-token-module#55]
Hello,

I'm testing secure_token_encrypt_uri but can not find option to set expiration time.

Thanks.

**Comment by erankor** [comment]
URL encryption has no expiration, it just encrypts/decrypts the URL... 
The different types of tokens supported by this module (Akamai, CloudFront, etc.) have an expiration.

**Comment by hien** [comment]
Ok. Thank you. I solved by using secure_links module along with secure-token.

**Comment by francoism90** [comment]
@hien Would it be possible to post your configs?
