### ISSUE TITLE
Decrypt $args

### ISSUE THREAD

**Issue by xXxSPYxXx** [kaltura/nginx-secure-token-module#56]
Hello,
You can make sure that the module decrypts not only $uri, but also arguments $args.
Example:
```
  location ~* "^/stream/(.*)" {

    secure_token_encrypt_uri on;
    secure_token_encrypt_uri_key 112313123131313123;
    secure_token_encrypt_uri_iv  1231312312331231;
    secure_token_encrypt_uri_part $1;
}
```
Its work, all fine.

```
  location ~* "^/stream/" {

    secure_token_encrypt_uri on;
    secure_token_encrypt_uri_key 112313123131313123;
    secure_token_encrypt_uri_iv  1231312312331231;
    secure_token_encrypt_uri_part $arg_somearg;
}
```
Its didnt work, send error log

> ngx_http_secure_token_get_encryted_part: failed to find the encrypted uri part

**Comment by erankor** [comment]
Sorry, this is not supported.
The uri decryption in this module was developed for a very specific use case, depending on your use case, maybe you can use a more generic encryption/decryption module like https://github.com/openresty/encrypted-session-nginx-module.

**Comment by xXxSPYxXx** [comment]
Solved https://github.com/kaltura/nginx-secure-token-module/pull/57
