### ISSUE TITLE
Can't find a way to compile it on windows.. maybe you got it ?

### ISSUE THREAD

**Issue by SAMYEL06** [kaltura/nginx-secure-token-module#58]
Hello,

I'm unable to compile it with rtmp module on Windows.. Mostly because it says that it doesn't found some makefiles .. Just don't get it at all.. :/

I thought that the author might have had it compiled for his own use and might be okay to share it with me ? (through a hosting file service like 1fichier.com or else ?)

I'm kind of tired and sad of failing, maybe you can help me... 

Thanks ! 

MrFrieza..

**Comment by erankor** [comment]
Sorry, never tried to compile any of our nginx modules under Windows. If there are specific compilation errors that you're getting, you can paste them here, and I'll try to help
