### ISSUE TITLE
SAMPLE-AES and #EXT-X-KEY

### ISSUE THREAD

**Issue by mlevkov** [kaltura/nginx-secure-token-module#61]
Hello,

We have discovered that when using the Secure Token Module in combination with DRM system for SAMPLE-AES encryption, the generated output contained within #EXT-X-KEY, is prepending policy information, which complicates key retrieval. 

The expected output in sub-variant should look like the following:
```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://drmserver?assetId=014bkssd9amw9yy5",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```

However, when secure token module is turned on for a given HLS location with "secure_token_types application/vnd.apple.mpegurl;" directive, it has appended details that are not necessary within the uri of 
```
#EXT-X-KEY:
skd://drmserver?assetId=014bkssd9amw9yy5?Policy=<...removed for security...>&Signature=<...removed for security...>&Key-Pair-Id=<... removed for security...>
```
(Note: I removed sensitive information for security purposes). 

Please note that 
```
?Policy=<...removed for security...>&Signature=<...removed for security...>&Key-Pair-Id=<... removed for security...>`
```
 is added to the URI. 

We could modify the https://github.com/kaltura/nginx-secure-token-module/blob/master/ngx_http_secure_token_m3u8.c to handle SAMPLE-AES method without adding 
```
?Policy=<...removed for security...>&Signature=<...removed for security...>&Key-Pair-Id=<... removed for security...>
``` 
detail, however, if you are able to do so then I would appreciate that very much. 

When a secure token module is set to None within a 'location', the output  for uri within #EXT-X-KEY does not prepend the 
```
?Policy=<...removed for security...>&Signature=<...removed for security...>&Key-Pair-Id=<... removed for security...>
```
However, when secure token module is set to `secure_token_types application/vnd.apple.mpegurl;`, then the
`?Policy=<...removed for security...>&Signature=<...removed for security...>&Key-Pair-Id=<... removed for security...>` is added across all urls and there is no way to **exclude** propagation to #EXT-X-KEY section. 
I cannot classify this as a bug or possible feature to turn it on of off, however, it definitely is not necessary for #EXT-X-KEY section uri attribute.

**Comment by erankor** [comment]
Try this pull - #62

**Comment by mlevkov** [comment]
Will try that in a bit.

**Comment by mlevkov** [comment]
Reporting back. The change is producing the output as expected, however, more testing is needed. Will report back on the outcome tomorrow.

**Comment by mlevkov** [comment]
I am happy to inform you that this change has been test thoroughly and results are consistently accurate, as expected. Please feel free to merge it to your main branch. This change fixes the issue.

**Comment by erankor** [comment]
Merged, thanks

**Comment by mlevkov** [comment]
Welcome, thank you for a quick turn around.
