### ISSUE TITLE
Nginx 1.17.0 error during compiling

### ISSUE THREAD

**Issue by andygr** [kaltura/nginx-secure-token-module#74]
Hello,

I have nginx 1.17.0 and i am trying to compile it with the secure-token-module but i am getting an error.
This is the configure command:
`./configure --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_v2_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-pcre --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-mail_ssl_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-mail=dynamic --with-stream=dynamic --add-module=/tmp/nginx-secure-token-module-master`

Configure command has been completed, however make command failed:

```
/tmp/nginx-secure-token-module-master/iijpta/ngx_http_secure_token_iijpta.c:123:8: error: implicit declaration of function 'htobe64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        end = htobe64(end);
              ^
/tmp/nginx-secure-token-module-master/iijpta/ngx_http_secure_token_iijpta.c:130:8: error: implicit declaration of function 'htobe32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        crc = htobe32(crc);
              ^
/tmp/nginx-secure-token-module-master/iijpta/ngx_http_secure_token_iijpta.c:130:8: note: did you mean 'htobe64'?
/tmp/nginx-secure-token-module-master/iijpta/ngx_http_secure_token_iijpta.c:123:8: note: 'htobe64' declared here
        end = htobe64(end);
              ^
2 errors generated.
*** Error code 1

Stop.
make[1]: stopped in /tmp/nginx-1.17.0
*** Error code 1

Stop.
make: stopped in /tmp/nginx-1.17.0

``` 

Thank you
Andrew

**Comment by erankor** [comment]
Please try #75 
@kuroishi, would be great if you can test it as well, to make sure iijpta still works

**Comment by kuroishi** [comment]
ok. I'll check it soon.

**Comment by kuroishi** [comment]
I've checked #75 and it works well as I expect.

// BTW, is there the systems without htobe{32,64}?

**Comment by erankor** [comment]
Thanks @kuroishi.
Maybe it can be solved by adding some #include, but I preferred not to get into it, I'm using these macros in nginx-vod-module and never had any problems with it...

**Comment by andygr** [comment]
Hello and thank you for the quick response. 

Just to clarify the change that I need to do. 
I need to replace the current file with the one in the #75  ? 

Also do you have an example of how to use the secure token module without CDN?

Kr
Andrew

**Comment by erankor** [comment]
Yes, replace the file and make sure it compiles for you.
If you don't use a CDN, you'd need some module to validate the tokens, you can use for example nginx's secure token module, or https://github.com/kaltura/nginx-akamai-token-validate-module

**Comment by andygr** [comment]
Thank you @erankor 

If i add the token in the HLS manifest, how will add the same token in the bitrate manifests and ts files?
I can't modify the manifest files because are stored in S3, however i saw that you have a vod module for on the fly packaging which can modify the manifest and add the tokens. 
Do i need it or nginx and player will handle it? I am trying to avoid modifying the content of the manifest files

**Comment by erankor** [comment]
This is what this module does... it enables you to add tokens as query params on URLs returned in HLS/DASH manifests.

**Comment by andygr** [comment]
Thanks @erankor ,
Later on today will try to compile nginx and hopefully will be ok. 

Also i checked couple of tickets for how to configure nginx for secure token. I endup with this config as a starting point, can you please let me know if i need to change something? Also will work for live and VoD?

```
http {
	secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
                param_name token
	}

	server {
        listen 80;

		if ($arg_token) {
			set $test_token $arg_token;
		}

		if ($cookie_token) {
			set $test_token $cookie_token;
		}

		location /hls/ {
			proxy_pass http://original-live-domain;

                        akamai_token_validate on;
                        akamai_token_validate $test_token;
			akamai_token_validate_key 1234;

                        secure_token $token;
                        secure_token_types text/xml application/vnd.apple.mpegurl;
                        secure_token_content_type_f4m text/xml;
                        secure_token_expires_time 100d;
			secure_token_query_token_expires_time 1h;
                        secure_token_tokenize_segments on;
		}
	}
}
```


Thanks
Andrew

**Comment by erankor** [comment]
Looks ok to me.
Live is a bit problematic, because the tokens are generated using the server clock, and therefore the player may see various URLs for a given segment over time. Apple player don't accept it and fail. 
Our solution for this is to use non-expiring tokens for live - add `start @0; end max;` to the token block.

**Comment by andygr** [comment]
Hi @erankor ,

The changes worked , i was able to compile it with both modules

```
nginx version: nginx/1.17.0
built by clang 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
built with OpenSSL 1.0.2s  28 May 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_v2_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-pcre --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-mail_ssl_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-mail=dynamic --add-module=/tmp/nginx-secure-token-module-master --add-module=/tmp/nginx-akamai-token-validate-module-master
```

Thank you !!

**Comment by andygr** [comment]
Can you please let me know how to generate the token?
Shall i use this file?
https://github.com/kaltura/server/blob/Lynx-12.14.0/alpha/apps/kaltura/lib/storage/urlTokenizers/kAkamaiSecureHDUrlTokenizer.php

because i am getting this error: PHP Fatal error:  Class 'kUrlTokenizer' not found 

Also i am wondering if i can use the python version:
https://qa-myakamai.cs52.force.com/customers/s/article/Ever-wondered-how-to-protect-your-assets-with-token-auth-EdgeAuth-2-0?language=en_US

**Comment by andygr** [comment]
Actually i downloaded the Akamai scripts from Akamai portal and seems to be ok now:


* Generate a token that allows access to a specific set of urls with wildcards:
```
python akamai_token_v2.py --window=300 --key=aa11bb22 --acl='/hls/*'
exp=1560981120~acl=/hls/*~hmac=7be6833c3bdf42323b3dda5e97a76699e9c1f84cc3bd474bace26309f1c2fa9c

```
I believe, I need to construct the URL like this:

`/hls/7samurai/playlist.m3u8?exp=1560981120~acl=/hls/*~hmac=7be6833c3bdf42323b3dda5e97a76699e9c1f84cc3bd474bace26309f1c2fa9c`

**Comment by erankor** [comment]
I didn't check the signature, but the structure looks ok, note that for production use, makes sense to sign the video id in the acl. If you use acl=/hls/* the token grants access to the entire catalog

**Comment by andygr** [comment]
I could comlile nginx with the secure token modules
