### ISSUE TITLE
Nginx 1.17.0 & Secure/Akamai token issue

### ISSUE THREAD

**Issue by andygr** [kaltura/nginx-secure-token-module#76]
Hello,

I compiled Nginx with the following modules:

`configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_v2_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-pcre --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-mail_ssl_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-mail=dynamic --add-module=/tmp/nginx-secure-token-module-master --add-module=/tmp/nginx-akamai-token-validate-module-master`

and i added the follow config for the akamai token:

in HTTP
```
secure_token_akamai $token {
		key aa11bb22;
		acl "$secure_token_baseuri_comma*";
                param_name token;
    }

```

in Server
```
if ($arg_token) {
			set $test_token $arg_token;
        }

	if ($cookie_token) {
			set $test_token $cookie_token;
       	}
```

and in the location
```
akamai_token_validate $test_token;
           akamai_token_validate_key aa11bb22;
	   secure_token $token;
	   secure_token_types text/xml application/vnd.apple.mpegurl;		
	   secure_token_content_type_f4m text/xml;
	   secure_token_expires_time 100d;
	   secure_token_query_token_expires_time 1h;
           secure_token_tokenize_segments on;
```

I used the akamai python script to generate the token:
`token=exp=1562280369~acl=/hls/*~hmac=c3b073ebed05a4b462dc0cdeda3df4987cc7b79d67ccafda5ef59868fbeff4a6
`

and the request for the manifest was successful:
```
Request URL: https://example.com/hls/5d134afe91b970.80939375/playlist.m3u8?token=exp=1562280369~acl=/hls/*~hmac=c3b073ebed05a4b462dc0cdeda3df4987cc7b79d67ccafda5ef59868fbeff4a6
Request Method: GET
Status Code: 200 OK

```

However the request for the other manifests was returning 403:
```
Request URL: https://example.com/hls/5d134afe91b970.80939375/768_432_1000_5d134afe91b970.80939375.m3u8
Request Method: GET
Status Code: 403 Forbidden
```

Do i need to send (via the player) the same token parameters for all m3u8 as well as ts files ?

Can you please explain to me how the request should work?

Thanks
ANdrew

**Comment by erankor** [comment]
No, the player doesn't need to pass the token, that is the purpose of this module.
From what you wrote, it seems the module doesn't manipulate the manifest, most probable cause is that secure_token_types doesn't have the required type. There are multiple mime-types for m3u8 (application/x-mpegURL / vnd.apple.mpegURL) maybe the one in the config doesn't match the one returned from the server.

**Comment by andygr** [comment]
This worked by using the correct mime-type
